export { ComponentButton as Button } from './Button/Button'
export { ComponentNavigation as Navigation } from './Navigation/Navigation'
export { ComponentParagraph as Paragraph } from './Paragraph/Paragraph'
export { ComponentCard as Card } from './Card/Card'
export { ComponentRate as Rate } from './Rate/Rate'
